services:
  erdmannfreunde.contao_news_newsletter.listener.data_container.news.newsletter_operation_button:
    class: ErdmannFreunde\ContaoNewsNewsletterBundle\EventListener\DataContainer\News\NewsletterOperationButtonListener
    public: true

  erdmannfreunde.contao_news_newsletter.listener.data_container.news_archive.notification_choices:
    class: ErdmannFreunde\ContaoNewsNewsletterBundle\EventListener\DataContainer\NewsArchive\NotificationChoicesListener
    arguments: ['@database_connection']
    public: true
